name: ayvu_app
description: The Ayvu Project consists of a set of tools that collect language data through audio recordings and a geographic reference of where the person acquired a particular accent. Available through a mobile application, which allows people without any prior knowledge of technology to access and use these utilities.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.14
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
