name: ayvu_app
description: The Ayvu Project consists of a set of tools that collect language data through audio recordings and a geographic reference of where the person acquired a particular accent. Available through a mobile application, which allows people without any prior knowledge of technology to access and use these utilities.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  path_provider: ^2.0.14
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0 
  geolocator: ^13.0.2
  intl: ^0.20.2
  sqflite: ^2.4.1
  path: ^1.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ayvu_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
